import {
  LayoutDashboard,
  BarChart3,
  PieChart,
  Activity,
  TrendingUp,
  LineChart,
  Gauge,
  Monitor,
  Database,
  Shield,
  Bell,
  FileText,
  Settings,
  Cpu,
  Thermometer,
  Droplets,
  Zap,
  Radio,
  Radar,
  Eye,
  Layers,
  Grid3X3,
  Table,
  Calendar,
  List,
  Network,
  Globe,
  Server,
  HardDrive,
  type LucideIcon,
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  'layout-dashboard': LayoutDashboard,
  'bar-chart-3': BarChart3,
  'pie-chart': PieChart,
  'activity': Activity,
  'trending-up': TrendingUp,
  'line-chart': LineChart,
  'gauge': Gauge,
  'monitor': Monitor,
  'database': Database,
  'shield': Shield,
  'bell': Bell,
  'file-text': FileText,
  'settings': Settings,
  'cpu': Cpu,
  'thermometer': Thermometer,
  'droplets': Droplets,
  'zap': Zap,
  'radio': Radio,
  'radar': Radar,
  'eye': Eye,
  'layers': Layers,
  'grid': Grid3X3,
  'table': Table,
  'calendar': Calendar,
  'list': List,
  'network': Network,
  'globe': Globe,
  'server': Server,
  'hard-drive': HardDrive,
};

export function resolveIcon(name: string): LucideIcon {
  return ICON_MAP[name] ?? FileText;
}

export const AVAILABLE_PAGE_ICONS = Object.keys(ICON_MAP);
