/**
 * TypeScript interfaces mirroring the plant_survey.json schema
 * generated by the jsonFormatter consultancy tool.
 */

export interface PlantSurvey {
  schema_version: string;
  survey_metadata?: SurveyMetadata;
  client_name: string;
  plants: PlantSurveyPlant[];
}

export interface SurveyMetadata {
  survey_date?: string;
  technician_name?: string;
  client_contact_name?: string;
  client_contact_role?: string;
  notes?: string;
}

export interface PlantSurveyPlant {
  plant_name: string;
  location?: PlantLocation;
  industrial_diagram?: IndustrialDiagram;
  scada_system?: ScadaSystem;
  processes: PlantSurveyProcess[];
}

export interface PlantLocation {
  address?: string;
  municipality?: string;
  province?: string;
  country?: string;
  coordinates?: { latitude: number; longitude: number };
}

export interface IndustrialDiagram {
  available: boolean;
  format?: string;
  filename?: string;
  notes?: string;
}

export interface ScadaSystem {
  vendor?: string;
  protocol?: string;
  historian?: string;
  export_capability?: string;
  notes?: string;
}

export interface PlantSurveyProcess {
  process_name: string;
  process_description?: string;
  siguiente_proceso?: string | string[] | null;
  rama_de?: string | string[] | null;
  sensors: PlantSurveySensor[];
}

export interface PlantSurveySensor {
  sensor_name: string;
  sensor_alias?: string;
  sensor_type?: string;
  unit?: string;
  description?: string;
  variable_type: 'continuous' | 'binary' | 'categorical' | 'discrete' | 'qualitative';
  instrument_role?: 'sensor' | 'actuator' | 'setpoint' | 'alarm';
  min_value?: number | null;
  max_value?: number | null;
  sampling_frequency?: { value: number; unit: string };
  reading_frequency?: { value: number; unit: string };
  preprocessing?: string | null;
  causality?: 'endogenous' | 'exogenous' | 'interna' | 'externa';
  categorical_values?: string[];
  equipment_name?: string;
  known_data_issues?: string | null;
  notes?: string | null;
}
